[package]
name = "tigris-sim"
version = "0.1.0"
edition = "2021"

[workspace]

[[bin]]
name = "tigris-sim"
path = "src/main.rs"

[[bin]]
name = "tigris-muddle"
path = "src/bin/tigris-muddle.rs"

[[bin]]
name = "tigris-muddle-window"
path = "src/bin/tigris-muddle-window.rs"

[[bin]]
name = "tigris-muddle-macroquad"
path = "src/bin/tigris-muddle-macroquad.rs"

[dependencies]
court-core = { git = "https://github.com/giodl73-repo/COURT.git", package = "court-core", branch = "master" }
macroquad = "0.4"
muddle-cli = { git = "https://github.com/giodl73-repo/MUDDLE.git" }
muddle-core = { git = "https://github.com/giodl73-repo/MUDDLE.git" }
muddle-macroquad = { git = "https://github.com/giodl73-repo/MUDDLE.git" }
muddle-window = { git = "https://github.com/giodl73-repo/MUDDLE.git" }
rally-core = { git = "https://github.com/giodl73-repo/RALLY.git" }

[dev-dependencies]
racket-core = { git = "https://github.com/giodl73-repo/RACKET.git", package = "racket-core", branch = "master" }
